initial Commit
UC-Technologies/vyatha-services pull request #10
Opened 2023-09-13 18:59 UTC by webdotmilans

Js-files of student & admin login and admin model are added

2023-09-14 11:38 UTC, hereisadi requested changes

2023-09-14 11:38 UTC, hereisadi commented on package.json
Why bcryptjs? bcrypt has already been installed.

2023-09-14 11:38 UTC, hereisadi commented on src/routes/student/studentLogin.js
Define the student login function in Controllers folder like this:
`const home = (req, res) => {
  res.send(
    "<p>Welcome to Vyatha api</p>"
  )
};
module.exports = {
  home,
};
`


You have to define the routes in UserRoutes.js like this:
`router.get("/", HomeController.home)`

2023-09-14 11:38 UTC, hereisadi commented on src/app.js
You need not to do any changes in app.js file. 
create routes in UserRoutes.js file and rest will be handled automatically.
app.js has already been configured.

2023-09-18 19:13 UTC, hereisadi requested changes

2023-09-18 19:13 UTC, hereisadi commented on src/controllers/UserController.js
> +    console.error(error.message);
`console.log(error)` will do the work

2023-09-18 19:13 UTC, hereisadi commented on src/controllers/UserController.js
> +const adminLogin = async (req, res) => {
similarly do the changes for admin login too

2023-09-18 19:13 UTC, hereisadi commented on src/controllers/UserController.js
> +    res.status(500).send("Internal server error");
send error message in json format.

2023-09-18 19:13 UTC, hereisadi commented on src/routes/UserRoutes.js
> +router.post('/vyatha/api/studentLogin',userController.studentLogin);
just give ("/studentLogin") and similary for adminLogin & add /vyatha/api is app.js

2023-09-21 08:15 UTC, hereisadi requested changes
take pull of `dev` and solve conflicts

2023-09-22 18:59 UTC, hereisadi requested changes

2023-09-22 18:59 UTC, hereisadi commented on src/app.js
> +module.exports = app;
redundant export.

2023-09-22 20:29 UTC, hereisadi approved these changes

2023-09-24 13:57 UTC, Himangshu-101 approved these changes

2023-09-24 17:11 UTC, merged