Add DbCollection Add Signup Model in User.js
UC-Technologies/vyatha-services pull request #8
Opened 2023-09-13 17:07 UTC by Neeraj-Bora

2023-09-14 11:19 UTC, hereisadi requested changes

2023-09-14 11:19 UTC, hereisadi commented on src/db/DbCollection.js
There is no need to create this DbCollection.js file. The schema which you have declared should be in models folder.

2023-09-14 11:19 UTC, hereisadi commented on src/models/User.js
You have to define the schema and models here in this file.
Define the signup function in Controllers folder.

2023-09-14 11:19 UTC, hereisadi commented on src/models/User.js
> +app.listen(3000,()=>{
app.listen is done in index.js and need not to be done in every individual file.

2023-09-14 11:19 UTC, hereisadi commented on src/models/User.js
Use try catch block to properly handle errors with status code.
Moreover, throw an error "user already exists" if user has already created an account, use bcrypt to hash the password before storing it in db.

2023-09-24 12:36 UTC, Himangshu-101 commented
> _ No description provided. _

Write proper descriptions about your commits.  If you see merge conflicts in your PR, then take the necessary actions to remove those conflicts too !

2023-10-10 17:57 UTC, hereisadi requested changes
![image](https://github.com/UC-Technologies/vyatha-services/assets/106585924/4190f165-6998-4124-8647-dabac97b9dab)
Fix these errors, and we will be okay to proceed further with this PR

2023-10-10 17:57 UTC, hereisadi commented on src/controllers/UserController.js
> +              return res.status(422).json({error:"User already exists"});
Preferred status code should be 400 in this case. Please go through https://developer.mozilla.org/en-US/docs/Web/HTTP/Status and carry out changes if required.

2023-10-10 17:57 UTC, hereisadi commented on src/controllers/UserController.js
> +  app.post("/signup",async(req,res)=>{
you have already created `router.post("/signup", )` in UserRoutes.js. Here, you need only to define the signup function. Correct it like below:
`const signup = (req,res) => { }`

2023-10-11 20:56 UTC, Himangshu-101 requested changes

2023-10-11 20:56 UTC, Himangshu-101 commented on src/controllers/UserController.js
> +module.exports = {
write module exports as one time only... below in the file it is already used.
So export signUp there only (home is already exported) and remove this one

2023-10-12 12:43 UTC, hereisadi requested changes

2023-10-12 12:43 UTC, hereisadi commented on src/routes/UserRoutes.js
> +router.post("/signup", userController.UserRoutes.signUp)
it should be `router.post("/signup", userController.signUp)`

2023-10-15 10:40 UTC, hereisadi commented on src/models/User.js
> +const app= express();
no need to importing express in model file

2023-10-15 10:40 UTC, hereisadi approved these changes

2023-10-15 11:57 UTC, Himangshu-101 approved these changes

2023-10-16 14:10 UTC, closed without merging